### PR TITLE
Match docs for multiple conditions on single column

### PR DESCRIPTION
**Pull request by davidguttman**
Code expects `op: '>='` but docs say `operation: '>='`:

``` js
albums.get({
  artist: 'David Bowie',
  release_year: [{
    operation: '>=',
    value: 1976
  }, {
    operation: '<='
    value: 1978
  }]
}, function(err, rows){ ... })
```

### CODE REVIEW

**Comment by brianloveswords** [comment]
Rad, thanks! I'll take a look at this today

**Comment by brianloveswords** [comment]
Well, I'll take a look at it RIGHT NOW, didn't realize it was such a minor fix!

**Comment by brianloveswords** [comment]
v0.8.5 published

**Comment by davidguttman** [comment]
Btw, this makes dealing with sql way nicer than I thought possible =)

**Comment by brianloveswords** [comment]
Thank you very much! :dancer:

**Pull request merged**
