### PR TITLE
`OR` queries

### PR DESCRIPTION
**Pull request by andrewhayward**
Adding `OR` functionality to `WHERE` queries - `... WHERE (<clause 1>) OR (<clause 2>) ...`:

```
table.get([{...}, {...}], ...)
```

Scratching my head as to how `... WHERE <clause 1> AND ((<clause 2>) OR (<clause 3>)) ...` might be enabled, but I think this is a step in the right direction.

### CODE REVIEW

**Comment by brianloveswords** [comment]
Thanks, I'll try to take a look at this later today!

**Comment by brianloveswords** [comment]
I MEAN TO LOOK AT THIS AND THEN I FAILED

Can you also write some docs for it in the readme?

**Comment by andrewhayward** [comment]
@brianloveswords - as you wish.

**Comment by brianloveswords** [comment]
I'M THE WORST, FUCK IT, LET'S DO IT LIVE.

**Pull request merged**
