### PR TITLE
Adding `where` clause to joined queries

### PR DESCRIPTION
**Pull request by andrewhayward**
Including `relationships` in a `get` is ignoring the query, seemingly because you're not adding `whereSql` in the `withJoin` sub-function.

### CODE REVIEW

**Comment by brianloveswords** [comment]
AH, my bad. Any chance of including a test? If not I can throw one in. Thanks!

**Comment by andrewhayward** [comment]
Yep, that can be done.

**Comment by andrewhayward** [comment]
I've not touched the sqlite test file - will happily add tests for that too, but there are several tests already there that are commented out, including one for relationships, so not sure what state that's in.

**Comment by brianloveswords** [comment]
Rad, yeah, I can handle the sqlite file. Thanks!!

**Comment by brianloveswords** [comment]
Added you to `AUTHORS` file, published 0.4.1

**Pull request merged**
