### PR TITLE
Nested relationships

### PR DESCRIPTION
**Pull request by andrewhayward**
This adds a new property, `relationshipsDepth`, to the query options, which allows relationships to go more than one level deep (which is the default, and current behaviour). Relationships automatically stop if a circular reference is found, regardless of the depth specified.

It also opens up a few new options for `relationships`:
- **Object** - this is the same as it was, and assumes user specified relationships
- **Boolean** - this is the same as it was, and uses any defined relationships if `true`
- **Number** - assumes you meant `relationshipsDepth`, and uses any defined relationships
- **Array** - uses only the specified relationships, as taken from those defined in the model
- **String** - uses the specified relationship, as taken from those defined in the model

### CODE REVIEW

**Comment by brianloveswords** [comment]
Still working on breaking this. I checked out `4a-get.test.js`, I can't remember why those tests were commented out. I reactivated them and they pass, so I committed that to master. If you want to rebase or merge from `master` and try to write some tests against sqlite, that would be rad. I also made travis stop trying to test against 0.8 because that's broken right now (both because of npm using `^` instead of `~` and my use of `setImmediate` in places).

**Comment by brianloveswords** [comment]
I might have broken it: this doesn't seem to work with `createReadStream`:

``` js
// in 6-createreadstream.test.js
test('table.createReadStream: nested relationships', function (t) {
  useDb(t, tables, function (db, done) {
    const user = makeUserTable(db)
    const book = makeBookTable(db)
    const review = makeReviewTable(db)

    review.createReadStream({}, {
      debug: true,
      relationships: true,
      relationshipsDepth: -1
    }).pipe(concat(function (rows) {
      t.ok(rows[0].book.author, 'should not be undefined') // FAILS
      t.end()
    }))
  })
})
```

(Note, I fixed the `make` functions to express the relationships on `6-createreadstream.test.js` before trying to run this)

**Comment by brianloveswords** [comment]
Found another way to break it:

``` js
// in 4-get.test.js
function makeBookTable(db) {
  //...
     relationships: {
      author: {
        type: 'hasOne',
        local: 'author_id',
        foreign: { table: 'user', key: 'id' },
      },
     // Add new hasMany relationship for `reviews`
      reviews: {
        type: 'hasMany',
        local: 'id',
        foreign: { table: 'review', key: 'book_id' },
        optional: true,
      }
  //..
}
```

I get the following error:

```
...
ok 12 no errors
ok 13 We've found Mr Saunders
ok 14 no errors
ok 15 All of author's books found correctly
SELECT `review`.`id` AS `review:@:id`,`review`.`book_id` AS `review:@:book_id`,`review`.`link` AS `review:@:link`,`review:@:book`.`id` AS `review:@:book:@:id`,`review:@:book`.`author_id` AS `review:@:book:@:author_id`,`review:@:book`.`title` AS `review:@:book:@:title`,`review:@:book`.`release_date` AS `review:@:book:@:release_date`,`review:@:book:@:author`.`id` AS `review:@:book:@:author:@:id`,`review:@:book:@:author`.`first_name` AS `review:@:book:@:author:@:first_name`,`review:@:book:@:author`.`last_name` AS `review:@:book:@:author:@:last_name`,`review:@:book:@:author`.`age` AS `review:@:book:@:author:@:age` FROM `review`  INNER  JOIN `book` AS `review:@:book` ON `review`.`book_id` = `review:@:book`.`id` INNER  JOIN `user` AS `review:@:book:@:author` ON `review:@:book`.`author_id` = `review:@:book:@:author`.`id`  WHERE `review`.`id` = 1   LIMIT 1

/Users/brian/projects/streamsql/lib/drivers/prototype.js:290
        context[property] = rows.map(function (row) {
                          ^
TypeError: Cannot set property 'reviews' of undefined
    at /Users/brian/projects/streamsql/lib/drivers/prototype.js:290:27
    at Object.resolve (/Users/brian/projects/streamsql/lib/callback-resolver.js:3:33)
    at /Users/brian/projects/streamsql/index.js:213:23
    at Object._onImmediate (/Users/brian/projects/streamsql/lib/drivers/prototype.js:528:5)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

**Comment by andrewhayward** [comment]
The first error is easy to fix - none of the new nested relationships logic had been added to `createReadStream`, which is (oddly enough) problematic. Refactored that in.

**Comment by andrewhayward** [comment]
Upon investigation, the second error was easy to resolve too. Context was broken in certain circumstances - should be ok now.

@brianloveswords - shall I commit the tests above, or do you want to do that? I'll add the sqlite tests shortly.

**Comment by brianloveswords** [comment]
@andrewhayward Go ahead and commit the tests – I can't actually write to this PR since it's off your branch

**Comment by andrewhayward** [comment]
@brianloveswords - tests committed, and mirrored in the respective SQLite files.

**Comment by andrewhayward** [comment]
Not sure why Travis is failing here. For some reason it's not getting books back when requesting all of them, but is otherwise fine. All tests pass locally for me.

**Comment by brianloveswords** [comment]
Hmm I'm gonna do some experimenting to see if I can't replicate that travis failure.

**Comment by brianloveswords** [comment]
I can't figure out why travis is failing – I can't replicate it locally or on my Arch server. I'm gonna merge this!

**Pull request merged**
